| Appendix B: Delimiter Example

| Delimiters allow a device to declare multiple uses for a control.

| Ideally, an application like a flight simulator would look for the controls that are specific to it. It would first
| search for Flight Simulation Devices attached to the system and then, if one was found, it would look for
| controls (usages) such as Flight Control Stick, Trigger, Rudder, Throttle, Landing Gear, Toe Brake, etc.
| The problem with a Flight Stick declaring these usages is that the same device can also be used as a generic
| joystick. A device declaring itself as a Flight Simulation Device would not be found by an application that
| searched for a Joystick usage.

| A problem that occurs with generic buttons on an application-specific device such as a Flight Stick is that
| different applications use the same buttons for different purposes, forcing the user to relearn the buttons for
| each application.

| Delimiters solve this problem by allowing multiple usages to be associated with a device or an individual
| control. Using delimiters, a hardware vendor can suggest usages for the buttons that will allow a consistent
| user interface across applications.

| Note: Delimiters are not allowed on top-level collections or arrays.
| The following example is a single device that can also be identified as a Flight Simulation Device, a Flight
| Stick or a generic Joystick. Most of the controls also have alternate mappings:
| • The axes of the stick are either a Flight Control Stick or a Pointer.
| • The hat switch can also be used as a Point of View control.
| • Each of the four buttons have alternate mappings:
| − Button 1 or Trigger
| − Button 2 or Weapons Select
| − Button 3, Electronic Counter Measures, or Flare Release
| − Button 4, Landing Gear, or Chaff Release
| Buttons 3 and 4 thus have two alternate usages.
| Note that the report generated by this Report descriptor is identical to that generated by the joystick example in Appendix A.

05 01 UsagePage(Generic Desktop),
15 00 LogicalMin(0),
09 04 Usage (Joystick),
a1 01 Collection(Application)
  05 02 UsagePage(Simulation Controls),
  09 bb Usage (Throttle),
  15 81 Logical Minimum (-127),
  25 7f Logical Maximum (127),
  75 08 Report Size (8),
  95 01 Report Count (1),
  81 02 Input (Data, Variable, Absolute),

  a9 01 Delimiter(Open),
    09 20          Usage (Flight Control Stick),
    0B 01 00 01 00 Usage (Generic Desktop: Pointer),
  a9 00 Delimiter(Close),

  a1 00 Collection (Physical),
    0B 30 00 01 00 Usage (Generic Desktop: X),
    0B 31 00 01 00 Usage (Generic Desktop: Y),
    95 02 Report Count (2),
    81 02 Input (Data, Variable, Absolute),
  c0 End Collection(),

  a9 01 Delimiter(Open),
    0b 20 00 05 00 Usage (Game Controls: Point of View),
    0b 39 00 01 00 Usage (Generic Desktop: Hat switch),
  a9 00 Delimiter(Close),

  15 00 Logical Minimum (0),
  25 03 Logical Maximum (3),
  35 00 Physical Minimum (0), 
  46 0e01 Physical Maximum (270),
  65 14 Unit (English Rotation: Length(1)),
  55 00 Unit Exponent (0),
  75 04 Report Size (4),
  95 01 Report Count (1),
  81 42 Input (Data, Variable, Absolute, Null State),

  a9 01 Delimiter(Open),
    0b 01 00 09 00 Usage (Buttons: Button 1),
    09 c0          Usage (Trigger),
  a9 00 Delimiter(Close),

  a9 01 Delimiter(Open),
    0b 02 00 09 00 Usage (Buttons: Button 2),
    09 c2          Usage (Weapons Select),
  a9 00 Delimiter(Close),

  a9 01 Delimiter(Open),
    0b 03 00 09 00 Usage (Buttons: Button 3),
    09 b7          Usage (Electronic Counter Measures),
    09 bd          Usage (Flare Release),
  a9 00 Delimiter(Close),

  a9 01 Delimiter(Open),
    0b 04 00 09 00 Usage (Buttons: Button 4),
    09 be          Usage (Landing Gear),
    09 b4          Usage (Chaff Release),
  a9 00 Delimiter(Close),

  15 00 Logical Minimum (0), 
  25 01 Logical Maximum (1),
  35 00 Physical Minimum (0), 
  45 01 Physical Maximum (1),
  95 04 Report Count (4),
  75 01 Report Size (1),
  65 00 Unit (None),
  81 02 Input (Data, Variable, Absolute),
c0 End Collection()
