| A.14 Graphic Equalizer
| In this example the controls of a stereo, 10 band graphic equalizer are defined. There are 11 fields defined
| for each channel; a master volume control that sets the overall gain of the channel, and 10 individual
| equalizer band gain controls. The gain of an equalizer band is defined by an 8-bit value that can vary
| between 0 and 255. Usage Descriptors are utilized to identify the center frequency and Q of the individual
| bands. This report descriptor results in a 22 byte report being generated by the device.
| The Graphic Equalizer usage declares that a Usage Descriptor must be associated with each band. Because
| the bands in each channel are identical, the respective bands in each channel point to the same Usage
| Descriptor. eg. Band 1 of both the right and left channels declare the same string index 1.

05 0c UsagePage(Consumer)
09 01 Usage(Consumer Control)
a1 01 Collection(Application)
  0A 61 01 Usage(Channel Left)
  a1 02 Collection(Logical)
    09 e0 Usage(Volume) ; Master volume control for channel
    15 00 Logical Minimum(0)
    26 ff 00 Logical Maximum(255)
    75 08 ReportSize(8)
    95 01 ReportCount(1)
    b1 02 Feature(Data, Var, Absolute)
    09 06 Usage(Graphic Equalizer)
    a1 02 Collection(Logical)
      05 0a UsagePage(Ordinal)
      09 01 Usage(Ordinal 1) ; Band 1, Cutoff Frequency = 31.25 Hz
      09 02 Usage(Ordinal 2) ; Band 2, CF = 62.5
      09 03 Usage(Ordinal 3) ; Band 3, CF = 125
      09 04 Usage(Ordinal 4) ; Band 4, CF = 250
      09 05 Usage(Ordinal 5) ; Band 5, CF = 500
      09 06 Usage(Ordinal 6) ; Band 6, CF = 1000
      09 07 Usage(Ordinal 7) ; Band 7, CF = 2000
      09 08 Usage(Ordinal 8) ; Band 8, CF = 4000
      09 09 Usage(Ordinal 9) ; Band 9, CF = 8000
      09 0a Usage(Ordinal 10) ; Band 10, CF = 16000
      89 01 String Minimum(1)
      99 0a String Maximum(10)
      95 0a ReportCount(10)
      b1 02 Feature(Data, Var, Absolute)
    c0 End Collection()
  c0 End Collection()

  05 0c UsagePage(Consumer)  <-- Added (else Ordinal Page is still in effect)
  0a 62 01 Usage(Channel Right)
  a1 02 Collection(Logical)
    09 e0 Usage(Volume) ; Master volume control for Channel
    95 01 ReportCount(1)
    b1 02 Feature(Data, Var, Absolute)
    09 06 Usage(Graphic Equalizer)
    a1 02 Collection(Logical)
      05 0a UsagePage(Ordinal)
      09 01 Usage(Ordinal 1) ; Band 1, CF = 31.25 Hz
      09 02 Usage(Ordinal 2) ; Band 2, CF = 62.5
      09 03 Usage(Ordinal 3) ; Band 3, CF = 125
      09 04 Usage(Ordinal 4) ; Band 4, CF = 250
      09 05 Usage(Ordinal 5) ; Band 5, CF = 500
      09 06 Usage(Ordinal 6) ; Band 6, CF = 1000
      09 07 Usage(Ordinal 7) ; Band 7, CF = 2000
      09 08 Usage(Ordinal 8) ; Band 8, CF = 4000
      09 09 Usage(Ordinal 9) ; Band 9, CF = 8000
      09 0a Usage(Ordinal 10) ; Band 10, CF = 16000
      89 01 String Minimum(1)
      99 0a String Maximum(10)
      95 0a ReportCount(10)
      b1 02 Feature(Data, Var, Absolute)
    c0 End Collection()
  c0 End Collection()
c0 End Collection()


| The above has been corrected by:
| 1. Selecting the Consumer Page before the Channel Right usage.
